# SPDX-FileCopyrightText: 2024 Scott Shawcroft for Adafruit Industries
#
# SPDX-License-Identifier: MIT

[tool.setuptools_scm]
# can be empty if no extra settings are needed, presence enables setuptools-scm
